name: Build & deploy Docker
on: [ workflow_dispatch ]

env:
  RELEASE: 20210601

jobs:
  rootfs-image:
    name: Build the release docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download RootFS
        run: make RELEASE=${{ env.RELEASE }} download
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build & publish Docker image
        uses: docker/build-push-action@v3
        with:
          build-args: RELEASE=${{ env.RELEASE }}
          context: .
          platforms: linux/riscv64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/archriscv:${{ env.RELEASE }}

  latest-image:
    name: Build the latest docker image
    needs: rootfs-image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build & publish Docker image
        uses: docker/build-push-action@v3
        with:
          build-args: RELEASE=${{ env.RELEASE }} REPO=${{ secrets.DOCKERHUB_USERNAME }}
          context: .
          file: latest.dockerfile
          platforms: linux/riscv64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/archriscv:latest

