name: Scheduled images update
on:
  workflow_dispatch:

jobs:
  rollout-images:
    name: Determine latest version
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.determine-release.outputs.release }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        id: determine-release
        name: Determine latest tarball
        run: |
          pip install beautifulsoup4
          echo "release=$(curl -L 'https://archriscv.felixc.at/images/' | python tools/scrapper.py | sed -e 's/archriscv-//' -e 's/.tar.zst//')" >> "$GITHUB_OUTPUT"
